# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

require './app/models/event'
require './app/models/user'

Event.destroy_all
User.destroy_all

# User

User.create(name: "Wonder Woman", email: "wonderful@gmail.com", image_url: "https://images.unsplash.com/photo-1536626420752-b144a129fde9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=668&q=80")

# Events

Event.create(name: "Shelf Road Craggin' Classic", city: "Canon Springs", state: "CO", event_type: "climbing", price: 35, start_date: "10-19-2018", end_date: "10-21-2018", description: "This October 19-21, head on down to the best limestone sport cragging Colorado has to offer, and with the American Alpine Club and CAMP USA, and be treated to a weekend of climbing, community, clinics, contests, beer, slideshows, films, giveaways, stewardship and fun.", event_url: "https://americanalpineclub.org/shelf-road-cc", image_url: "https://static1.squarespace.com/static/55830fd9e4b0ec758c892f81/57bc7284f7e0abe0efbb523e/59417dc21b631bad37b19a74/1497464437416/_MG_1604.jpg", video_url: "https://www.youtube.com/embed/Cnjv_Brs2Bo")

Event.create(name: "Sea Otter Classic", city: "Monterey", state: "CA", event_type: "biking", price: 50, start_date: "04-11-2019", end_date: "04-14-2019", description: "Known as a sprawling and energetic “celebration of cycling,” Sea Otter is cycling’s North American season opener. Professional and amateur athletes alike make the annual pilgrimage to Sea Otter to participate in some of the sport’s most competitive and enduring events. Hundreds of pro cyclists, including national, world, and Olympic champions, attend Sea Otter to race and meet with fans.

Most of cycling’s racing disciplines are represented including mountain bike cross country, downhill, dual slalom, and short track racing. Road cyclists compete in circuit, criterium, and road racing. Also offered are a number of non-competitive recreational events for riders of all ages.

The Sea Otter Classic also hosts the world’s largest consumer bike exposition in North America. The Expo holds hundreds of vendors who display new products, distribute free samples, and offer great bargains. The four-day, action-packed festival includes an international food court, entertainment, bike demos, stunt shows, and activities for children.

", event_url: "http://www.seaotterclassic.com/", image_url: "https://www.wired.com/wp-content/uploads/images_blogs/playbook/2013/04/U3C0719edit.jpg", video_url: "https://www.youtube.com/embed/nXTNYnGZLSE")

Event.create(name: "Crested Butte Bike Week", city: "Crested Butte", state: "CO", event_type: "biking", price: 0, start_date: "06-27-2019", end_date: "06-30-2019", description: "Bike week is a multi-day celebration of all things mountain bike in the Gunnison Valley. We still have the big thigh burner of a singletrack race, the Fat Tire 40, but now CB Bike Week is more of a celebration of how mountain biking defines our community in the summer. Join us for clinics, a film festival, the Chainless Downhill World Championships, good beer, and a great party.", event_url: "http://www.cbchamber.com/chamberevents/cb-bike-week/", image_url: "https://travelcrestedbutte.com/wp-content/uploads/bike-week-feature.jpg", video_url: "https://www.youtube.com/embed/0cFSZCDMP_U")

Event.create(name: "Wydaho Rendezvous Teton Bike Festival", city: "Driggs", state: "ID", event_type: "biking", price: 89, start_date: "08-30-2019", end_date: "09-02-2019", description: "Just Like The Mountain Men Who Gathered Here Over A Century Ago To Trade Furs, Swap Lies, Eat, Drink, And Explore The Teton Mountain Range, Mountain Bikers From All Over The West Will Be Gathering In Teton Valley For A Weekend-Long Bike Festival That Offers Loads Of Fun Including:  Outstanding Riding And Clinics, Next Year Bike Demo’s Right Before Interbike, And Exceptional Entertainment!", event_url: "https://tetonbikefest.org/", image_url: "https://i2.wp.com/crankjoy.com/wp-content/uploads/2018/08/Teton-Mile-Sell.jpg?resize=1500%2C1000&ssl=1", video_url: "https://www.youtube.com/embed/RBJ9bMhCEZM")

Event.create(name: "Fjallraven US Classic", city: "Leadville", state: "CO", event_type: "hiking", price: "299", start_date: "08-27-2019", end_date: "08-30-2019", description: "The Classic trekking series embodies Fjällräven’s spirit. The communal trek is all about spending time in nature with a crew of like-minded people, creating lasting memories on the trail and sharing stories around the campfire. We get excited to introduce fans of Fjallraven to the Swedish trekking tradition in our beautiful backyard.", event_url: "https://classic.fjallraven.com/usa/classic-usa/about-classic-usa/", image_url: "https://www.outsideonline.com/sites/default/files/styles/full-page/public/2016/08/26/fjallraven-classic_h.jpg?itok=-kiFQlnk", video_url: "https://www.youtube.com/embed/lfy1c72XFgQ")

Event.create(name: "The One Day Hike", city: "Montgomery County", state: "MD", event_type: "hiking", price: 0, start_date: "05-04-2019", end_date: "05-04-2019", description: "The One Day Hike (ODH) comprises two concurrent, non-competitive hikes of 100 and 50 km (62.14 and 31.07 miles) that follow the C&O Canal towpath, and end in Bolivar, WV. The 100 km event (“100K”) starts at 3 AM from the Thompson Boat Center parking lot in Georgetown, Washington, DC; the 50 km event (“50K”) starts at 10 AM from Whites Ferry in Montgomery County, MD. Both hikes proceed along the towpath, crossing the footbridge into Harpers Ferry after mile marker 60, ending at the Bolivar Community Center. Hikers have until midnight to complete either hike.", event_url: "http://www.onedayhike.org/index.html", image_url: "http://www.onedayhike.org/images/NavMain/Main4.jpg", video_url: "https://www.youtube.com/embed/mtE64ZIlybg")

Event.create(name: "Desert Rats Trail Running Festival", city: "Fruita", state: "CO", event_type: "running", price: 120, start_date: "04-13-2019", end_date: "04-14-2019", description: "A weekend of fun and running on the beautiful trails near Fruita, Colorado. The weekend includes a Trail Marathon & 50K races along with an Awards Party on Saturday, and 10K & Half Marathon races on Sunday.", event_url: "https://geminiadventures.com/trail-running-festival/", image_url: "https://geminiadventures.com/trail-running-festival/", video_url: "https://www.youtube.com/embed/UxVKnb8DMYQ")

Event.create(name: "Flash Foxy", city: "Bishop", state: "CA", event_type: "climbing", price: 120, start_date: "03-22-2019", end_date: "03-24-2019", description: "Flash Foxy began as an online platform in 2014 to celebrate women climbing with women and to be a place where women could come to feel inspired by and connected to each other. In 2016 we held the inaugural Women’s Climbing Festival and now continue to bring women climbers together through a variety of events across the country.", event_url: "http://flashfoxy.com/", image_url: "http://flashfoxy.com/wp-content/uploads/2018/11/rsz_wcfchatt_2018_vglinskii_2-1024x683.jpg", video_url: "https://www.youtube.com/embed/CpsXwXGM2dQ")
Event.create(name: "Flash Foxy Summerfest", city: "Fayetteville", state: "WV", event_type: "climbing", price: 120, start_date: "06-07-2019", end_date: "06-09-2019", description: "Flash Foxy’s Summerfest is our first all-gender event that celebrates women, is put on by women but open to anyone to attend.", event_url: "http://flashfoxy.com/summerfest", image_url: "https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwjtqpmKpbLhAhWGCnwKHQY2BSIQjRx6BAgBEAU&url=http%3A%2F%2Fflashfoxy.com%2F&psig=AOvVaw0BT09KM0qPcnMCde597zdN&ust=1554324731986774", video_url: "https://www.youtube.com/embed/sMDfnebe4m0")
Event.create(name: "International Clibers' Festival", city: "Lander", state: "WY", event_type: "climbing", price: 120, start_date: "07-10-2019", end_date: "07-14-2019", description: "COME CELEBRATE THE CLIMBING LIFESTYLE! WITH COMPETITIONS, ART, FOOD, MUSIC, BEER, AND SO MUCH MORE, IT'S SURE TO BE A PARTY.", event_url: "https://www.climbersfestival.org/#welcome", image_url: "https://static1.squarespace.com/static/52d067f7e4b0309df5e103de/t/52fab709e4b08ba35fbe1207/1392162571068/serivice+project.jpg", video_url: "https://www.youtube.com/embed/w9qQhpt7Ggs")
Event.create(name: "Leavenworth Rock Fest", city: "Leavenworth", state: "WA", event_type: "climbing", price: 120, start_date: "07-10-2019", end_date: "07-14-2019", description: "Washington's largest rock climbing festival.", event_url: "https://www.leavenworthrockfest.com/#leavenworth-rockfest", image_url: "https://static1.squarespace.com/static/58b0dd8cf5e2315970fb3f26/t/5c8914be652dea6234e97cbc/1552487747932/Stanhope1.jpg", video_url: "https://www.youtube.com/embed/1W0VttBuiuE")
Event.create(name: "Joe's Valley Fest", city: "Emery County", state: "UT", event_type: "climbing", price: 256, start_date: "09-26-2019", end_date: "09-29-2019", description: "Festival goers will come from all four corners of the U.S for Joe's Valley Bouldering Fest. Shred your fingers climbing, eat pizza and do yoga in Utah.", event_url: "https://www.joesvalleyfest.com/", image_url: "https://www.joesvalleyfest.com/uploads/9/2/0/5/92054066/img-2965_orig.jpg", video_url: "https://www.youtube.com/embed/0nNu60QFOiM")
Event.create(name: "Hueco Rock Rodeo", city: "Hueco", state: "TX", event_type: "climbing", price: 100, start_date: "08-15-2019", end_date: "08-17-2019", description: "This 3-day grassroots climbing festival—presented by Five Ten and supported by Klean Kanteen and La Sportiva—celebrates the one-of-a-kind climbers and climbing of the Southwest.", event_url: "https://www.joesvalleyfest.com/", image_url: "https://static1.squarespace.com/static/55830fd9e4b0ec758c892f81/t/5c194758aa4a9943d93615c7/1545160550714/HRR_2019_Email.jpg?format=2500w", video_url: "https://player.vimeo.com/video/260129261?title=0&byline=0&portrait=0")

Event.create(name: "Royal Gorge Whitewater Festival", city: "Royal Gorge", state: "CO", event_type: "rafting", price: 100, start_date: "06-21-2019", end_date: "06-23-2019", description: "The 10th Annual Royal Gorge Whitewater Festival (RGWF) features whitewater competitions along with other land-based events to promote the outdoors and an active lifestyle.  The Arkansas River roars through the Royal Gorge and immediately enters Cañon City.  The Whitewater Park is in the western portion of Cañon City, just a little over a mile from the end of the Royal Gorge.  The RGWF celebrates the Arkansas River and highlights the many recreational opportunities it presents.", event_url: "http://www.royalgorgewhitewaterfestival.com/", image_url: "http://www.royalgorgewhitewaterfestival.com/uploads/2/8/4/0/28403233/published/192912328.png", video_url: "https://www.youtube.com/embed/SWgPEo7ojPQ")
Event.create(name: "CKS Paddlefest", city: "Buena Vista", state: "CO", event_type: "rafting", price: 0, start_date: "05-24-2019", end_date: "05-27-2019", description: "CKS Paddlefest has a mission to give back to the whitewater community. This year our beneficiary is the The River Fund at Chaffee County Community Foundation (CCCF). The River Fund will benefit our Buena Vista River Park and the community that feeds it. The River Park is the heart and soul of our community - whether you are a biker, hiker, kayaker, or here for the sights. CKS Main Street will also collect 1% of every sale to put towards the River Fund.", event_url: "http://www.royalgorgewhitewaterfestival.com/", image_url: "https://www.colorado.com/sites/default/files/BuenaVistaWhitewaterPark-Luke-Urbine-DSC_9890_0.jpg", video_url: "https://www.youtube.com/embed/QX4kXqZUI9I")
Event.create(name: "FIBArk", city: "Salida", state: "CO", event_type: "rafting", price: 0, start_date: "06-13-2019", end_date: "06-16-2019", description: "America's Oldest Whitewater Festival", event_url: "http://www.fibark.com/", image_url: "http://www.fibark.com/wp-content/uploads/2014/01/sup-race.jpg", video_url: "https://www.youtube.com/embed/BNrYhKYf9OE")

Event.create(name: "Into the Wild Running Festival", city: "Keensburg", state: "CO", event_type: "running", price: 45, start_date: "06-01-2019", end_date: "06-01-2019", description: "A festival event that benefits over 500 lions, tigers, bears, wolves, and other rescued animals.", event_url: "https://www.runintothewild.org/", image_url: "https://static.wixstatic.com/media/a16ed6_74cb0df16eff4481862ff4e3f4ce013e~mv2.jpg/v1/crop/x_531,y_0,w_1038,h_1038/fill/w_272,h_272,al_c,q_80,usm_0.66_1.00_0.01/TWAS_RITW17.jpg", video_url: "https://www.youtube.com/embed/Y3LUVkvEOgc")
